@main
struct RunTestsMain {
    static func main() async {
        runBracketRemovalTests()
        runHTTPTimeoutTests()
        runManualCooldownTests()
        runBacklogFlushContinuationTests()
        runProMetadataTests()
        runScrobbleEngineTests()
        runNowPlayingRateLimitTests()
        runLovedFeatureTests()
        runDedupTimestampToleranceTests()
        runListeningHistoryRecoveryTests()
        runDedupNearestMatchTests()
        runDedupRandomizedPreventionTests()
        runBacklogTests()
        runAdditionalBracketEdgeCaseTests()
        runAPITests()
        runManualScrobbleTests()
        runRelativeScrobbleTimeFormatterTests()
        runScrobbleLogStoreTests()
        runTextReplacementTests()
        runBackgroundGracePeriodTests()
        runScheduledBackgroundRecoveryTests()
        runAppleMusicRecentTracksImporterTests()
        runControlWidgetStatusTests()
        runICloudSyncTests()
        runSettingsDefaultsTests()
        runBacklogTimestampPreservationTests()
        runBacklogCleanupTests()
        await runStorageMaintenanceTests()
        runListeningHistoryScanTests()
        runConsecutivePlayGroupingTests()
        await runListenBrainzTests()
        finishTests()
    }
}
